/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package SC;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Jungle
 */


public class CustomerAccountHistoryPageJF extends javax.swing.JFrame {
 

    public CustomerAccountHistoryPageJF() 
    {
        initComponents();
    }
    
        
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Back = new javax.swing.JButton();
        nd = new javax.swing.JTextField();
        ND = new javax.swing.JTextField();
        nm = new javax.swing.JTextField();
        WD = new javax.swing.JTextField();
        DP = new javax.swing.JTextField();
        LN = new javax.swing.JTextField();
        confirm = new javax.swing.JButton();
        AB = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        NID = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SC/backbutton.jpg"))); // NOI18N
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 40, 260, 80));

        nd.setBackground(new java.awt.Color(0, 0, 0));
        nd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nd.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(nd, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 540, 220, 30));

        ND.setBackground(new java.awt.Color(0, 0, 0));
        ND.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ND.setForeground(new java.awt.Color(255, 255, 255));
        ND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NDActionPerformed(evt);
            }
        });
        getContentPane().add(ND, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 160, 30));

        nm.setBackground(new java.awt.Color(0, 0, 0));
        nm.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nm.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(nm, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, 150, 30));

        WD.setBackground(new java.awt.Color(0, 0, 0));
        WD.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        WD.setForeground(new java.awt.Color(255, 255, 255));
        WD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WDActionPerformed(evt);
            }
        });
        getContentPane().add(WD, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 410, 160, 30));

        DP.setBackground(new java.awt.Color(0, 0, 0));
        DP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DP.setForeground(new java.awt.Color(255, 255, 255));
        DP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DPActionPerformed(evt);
            }
        });
        getContentPane().add(DP, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 250, 170, 30));

        LN.setBackground(new java.awt.Color(0, 0, 0));
        LN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LN.setForeground(new java.awt.Color(255, 255, 255));
        LN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LNActionPerformed(evt);
            }
        });
        getContentPane().add(LN, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 320, 170, 30));

        confirm.setText("Confirm");
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });
        getContentPane().add(confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 620, -1, -1));

        AB.setBackground(new java.awt.Color(0, 0, 0));
        AB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AB.setForeground(new java.awt.Color(255, 255, 255));
        AB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABActionPerformed(evt);
            }
        });
        getContentPane().add(AB, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 400, 180, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("Customer Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, -1, -1));

        jLabel1.setBackground(new java.awt.Color(0, 153, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("National ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Withdraw");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("Deposit");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 250, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("Loan");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 320, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 0, 204));
        jLabel8.setText("National ID ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 540, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("Current Balance");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 400, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 51));
        jLabel9.setText("*Input Here");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 540, -1, -1));

        NID.setBackground(new java.awt.Color(102, 102, 102));
        NID.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\e153cdaec4f5ad40071d11bd0dfdc142.jpg")); // NOI18N
        getContentPane().add(NID, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1370, 710));

        jLabel3.setFont(new java.awt.Font("Algerian", 1, 35)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 255));
        jLabel3.setText("Customer Account history");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 540, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        dispose();
        new EmployeeHomePageJF().setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    private void NDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NDActionPerformed

    private void WDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WDActionPerformed

    private void LNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LNActionPerformed

    private void ABActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ABActionPerformed

    private void DPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DPActionPerformed

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
        // TODO add your handling code here:
        String NId=nd.getText();
        
        try{
            
	    Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            String accessFileName = "D:/Softe/Project SD/Bank/Main Bank/ProjectFile/StandardChartered/Fbank";
            String connURL = "jdbc:odbc:DRIVER={Microsoft Access Driver (*.mdb, *.accdb)};DBQ=" + accessFileName + ".accdb;";
            Connection con = DriverManager.getConnection(connURL, "", "");
            Statement stmt = con.createStatement();
           
           ResultSet rs = stmt.executeQuery("Select * from CustomerReport where NationalID='"+NId+"' ");
            
       
       if(rs.next())
            {
                String st1=rs.getString("NationalID");
                String st2=rs.getString("CustomerName");
                String st3=rs.getString("Withdraw");
                String st4=rs.getString("Deposit");
                String st5=rs.getString("Loan");
                String st6=rs.getString("AccountBalance");
                ND.setText(st1);
                nm.setText(st2);
                WD.setText(st3);
                DP.setText(st4);
                LN.setText(st5);
                AB.setText(st6);
                
            }
       else{JOptionPane.showMessageDialog(null, "Sorry! Wrong Input!");}
       
        } 
	catch (Exception err) {
            System.out.println("ERROR: " + err);
        }
  
        
    }//GEN-LAST:event_confirmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerAccountHistoryPageJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerAccountHistoryPageJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerAccountHistoryPageJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerAccountHistoryPageJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerAccountHistoryPageJF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AB;
    private javax.swing.JButton Back;
    private javax.swing.JTextField DP;
    private javax.swing.JTextField LN;
    private javax.swing.JTextField ND;
    private javax.swing.JLabel NID;
    private javax.swing.JTextField WD;
    private javax.swing.JButton confirm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nd;
    private javax.swing.JTextField nm;
    // End of variables declaration//GEN-END:variables
}
