/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package SC;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Jungle
 */
public class LoanServicePageJF extends javax.swing.JFrame {

    /**
     * Creates new form LoanServicePageJF
     */
    public LoanServicePageJF() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoanLabel = new javax.swing.JLabel();
        LoanAmount = new javax.swing.JTextField();
        BACK = new javax.swing.JButton();
        TAKA = new javax.swing.JButton();
        AccountBalance = new javax.swing.JTextField();
        Taka2 = new javax.swing.JTextField();
        Abalance = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        ID = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Password = new javax.swing.JTextField();
        PassWord = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoanLabel.setFont(new java.awt.Font("Utsaah", 3, 55)); // NOI18N
        LoanLabel.setText("Amount of Loan: ");
        getContentPane().add(LoanLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, -1, 70));

        LoanAmount.setBackground(new java.awt.Color(0, 0, 0));
        LoanAmount.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LoanAmount.setForeground(new java.awt.Color(255, 255, 255));
        LoanAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoanAmountActionPerformed(evt);
            }
        });
        getContentPane().add(LoanAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 270, 280, 40));

        BACK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SC/backbutton.jpg"))); // NOI18N
        BACK.setText("jButton2");
        BACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACKActionPerformed(evt);
            }
        });
        getContentPane().add(BACK, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 30, 240, 80));

        TAKA.setBackground(new java.awt.Color(204, 204, 255));
        TAKA.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TAKA.setText("TK");
        TAKA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TAKAActionPerformed(evt);
            }
        });
        getContentPane().add(TAKA, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 270, 50, 40));

        AccountBalance.setBackground(new java.awt.Color(0, 0, 0));
        AccountBalance.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AccountBalance.setForeground(new java.awt.Color(255, 255, 255));
        AccountBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccountBalanceActionPerformed(evt);
            }
        });
        getContentPane().add(AccountBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 330, 280, 40));

        Taka2.setBackground(new java.awt.Color(204, 204, 255));
        Taka2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Taka2.setText("   TK");
        Taka2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Taka2ActionPerformed(evt);
            }
        });
        getContentPane().add(Taka2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 330, 50, 40));

        Abalance.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        Abalance.setText("         Account Balance:");
        getContentPane().add(Abalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 420, 40));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 550, 90, 40));

        ID.setBackground(new java.awt.Color(0, 0, 0));
        ID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ID.setForeground(new java.awt.Color(255, 255, 255));
        ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDActionPerformed(evt);
            }
        });
        getContentPane().add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 400, 280, 40));

        jTextField3.setBackground(new java.awt.Color(204, 204, 255));
        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField3.setText("   TK");
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 400, 50, 40));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel1.setText("National ID :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, 240, 40));

        Password.setBackground(new java.awt.Color(0, 0, 0));
        Password.setForeground(new java.awt.Color(255, 255, 255));
        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });
        getContentPane().add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 470, 260, 40));

        PassWord.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        PassWord.setText("Password :");
        getContentPane().add(PassWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 470, 240, -1));

        bg.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SC/money--1571316-1920x1200.jpg"))); // NOI18N
        bg.setText("as");
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1390, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TAKAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TAKAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TAKAActionPerformed

    private void LoanAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoanAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoanAmountActionPerformed

    private void Taka2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Taka2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Taka2ActionPerformed

    private void AccountBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccountBalanceActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_AccountBalanceActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String PW=Password.getText();
        String Id =ID.getText();
        String ln=LoanAmount.getText();
        String AB=AccountBalance.getText();
      
        Database db= new Database();
        int Loan=Integer.parseInt(ln);
     
        int ABalance=Integer.parseInt(AB);  
                if(ABalance>Loan)
            {
        int Total=(ABalance+Loan);
        String TotalAccountBalance =Integer.toString(Total);
       
        String LoanAmount=Integer.toString(Loan);
       
        int result= db.CustomerLoan(TotalAccountBalance,LoanAmount,Id,PW);
        if (result==1)
       {
       dispose();
       new OurCommitmentJF().setVisible(true);
       }
           }
        else
        {
            JOptionPane.showMessageDialog(null, "Sorry! Your Amount Of loan exceeds Your Current Account Balance. You Have To Deposit more.");
        }
                
            
                
      
             
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDActionPerformed

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordActionPerformed

    private void BACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACKActionPerformed
        // TODO add your handling code here:
        dispose();
        new CustomerHomePageJF().setVisible(true);
    }//GEN-LAST:event_BACKActionPerformed

    /**DC
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoanServicePageJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoanServicePageJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoanServicePageJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoanServicePageJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoanServicePageJF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Abalance;
    private javax.swing.JTextField AccountBalance;
    private javax.swing.JButton BACK;
    private javax.swing.JTextField ID;
    public javax.swing.JTextField LoanAmount;
    private javax.swing.JLabel LoanLabel;
    private javax.swing.JLabel PassWord;
    private javax.swing.JTextField Password;
    private javax.swing.JButton TAKA;
    private javax.swing.JTextField Taka2;
    public javax.swing.JLabel bg;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
