/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package SC;

/**
 *
 * @author Jungle
 */
public class MoneyTransferPageJF extends javax.swing.JFrame {

    /**
     * Creates new form MoneyTransferPageJF
     */
    public MoneyTransferPageJF() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Dpst = new javax.swing.JTextField();
        PLn = new javax.swing.JTextField();
        ln = new javax.swing.JLabel();
        CB = new javax.swing.JLabel();
        Cb = new javax.swing.JTextField();
        NID = new javax.swing.JTextField();
        Pw = new javax.swing.JTextField();
        nid = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        confirm = new javax.swing.JButton();
        PasS = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SC/backbutton.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 40, 260, 80));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setText("     Amount Of Deposit");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 290, 40));

        Dpst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DpstActionPerformed(evt);
            }
        });
        getContentPane().add(Dpst, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 220, 30));

        PLn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PLnActionPerformed(evt);
            }
        });
        getContentPane().add(PLn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 220, 30));

        ln.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ln.setForeground(new java.awt.Color(255, 102, 0));
        ln.setText("Previous Loan Amount");
        getContentPane().add(ln, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 270, 30));

        CB.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        CB.setForeground(new java.awt.Color(255, 102, 0));
        CB.setText("Current Balance");
        getContentPane().add(CB, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 200, -1));

        Cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbActionPerformed(evt);
            }
        });
        getContentPane().add(Cb, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 210, 30));

        NID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NIDActionPerformed(evt);
            }
        });
        getContentPane().add(NID, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 210, 30));

        Pw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PwActionPerformed(evt);
            }
        });
        getContentPane().add(Pw, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, 210, 30));

        nid.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        nid.setForeground(new java.awt.Color(255, 102, 0));
        nid.setText("National ID");
        getContentPane().add(nid, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 150, 20));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("Password");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 130, 20));

        confirm.setBackground(new java.awt.Color(255, 153, 0));
        confirm.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        confirm.setText("Confirm");
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });
        getContentPane().add(confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 450, 90, 30));

        PasS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SC/MoneyTransferImage.jpg"))); // NOI18N
        PasS.setText("Confirm");
        getContentPane().add(PasS, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1358, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        new DoExtraPageJF().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
        // TODO add your handling code here:
        String Dp=Dpst.getText();
        String Ln=PLn.getText();
        String CB=Cb.getText();
        String Nid=NID.getText();
        String PW=Pw.getText();
        
        int DP=Integer.parseInt(Dp);
        int Cb=Integer.parseInt(Ln);
        int LN=Integer.parseInt(Ln);
        Database db=new Database();
        int TACB=(DP+Cb);
        if(DP>=LN)
        {
        DP=(DP-LN);
        LN=0;
        String Dep =Integer.toString(DP);
        String ln =Integer.toString(LN);
        String ACB =Integer.toString(TACB);
        
        int r=db.Customerdeposit(Nid,Dep,ln,ACB,PW);
        if(r==1)
        {
            dispose();
            new CustomerHomePageJF().setVisible(true);
        }
        
        }
        
        else if(DP<LN)
        {
            DP=(DP/2);
            LN=(LN-DP);
        String Dep =Integer.toString(DP);
        String ln =Integer.toString(LN);
        String ACB =Integer.toString(TACB);
        int r=db.Customerdeposit(Nid,Dep,ln,ACB,PW);
        if(r==1)
        {
            dispose();
            new CustomerHomePageJF().setVisible(true);
        }
        
        }
        
    }//GEN-LAST:event_confirmActionPerformed

    private void DpstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DpstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DpstActionPerformed

    private void PLnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PLnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PLnActionPerformed

    private void CbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbActionPerformed

    private void NIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NIDActionPerformed

    private void PwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PwActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MoneyTransferPageJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MoneyTransferPageJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MoneyTransferPageJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MoneyTransferPageJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MoneyTransferPageJF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CB;
    private javax.swing.JTextField Cb;
    private javax.swing.JTextField Dpst;
    private javax.swing.JTextField NID;
    private javax.swing.JTextField PLn;
    private javax.swing.JLabel PasS;
    private javax.swing.JTextField Pw;
    private javax.swing.JButton confirm;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel ln;
    private javax.swing.JLabel nid;
    // End of variables declaration//GEN-END:variables
}
