/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package SC;

import javax.swing.JOptionPane;

/**
 *
 * @author Jungle
 */
public class PayBillPageJF extends javax.swing.JFrame {

    /**
     * Creates new form PayBillJF
     */
    public PayBillPageJF() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        WD = new javax.swing.JTextField();
        AB = new javax.swing.JTextField();
        ND = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        PW = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        confirm = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SC/backbutton.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 90, 260, 80));

        WD.setBackground(new java.awt.Color(204, 255, 204));
        WD.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(WD, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 210, 40));

        AB.setBackground(new java.awt.Color(204, 255, 204));
        AB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(AB, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 190, 210, 40));

        ND.setBackground(new java.awt.Color(204, 255, 204));
        ND.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(ND, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 210, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Withdraw Amount");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        PW.setBackground(new java.awt.Color(204, 255, 204));
        PW.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(PW, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 360, 210, 40));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Password");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 360, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("National ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Account Balance");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 200, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SC/PayBillImage.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1358, 700));

        confirm.setBackground(new java.awt.Color(204, 204, 204));
        confirm.setText("Confirm");
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });
        getContentPane().add(confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 470, 120, 40));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 370, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        new DoExtraPageJF().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
        // TODO add your handling code here:
        String wd=WD.getText();
        String ab=AB.getText();
        String pw=PW.getText();
        String nd=ND.getText();
        
        Database db= new Database();
        int WD=Integer.parseInt(wd);
        int AB=Integer.parseInt(ab);
        if(AB>=WD)
            {
        int Total=(AB-WD);
        String TotalAccountBalance =Integer.toString(Total);
       
        String Withd=Integer.toString(WD);
       
        int result=db.CustomerWithdraw(TotalAccountBalance,Withd,pw,nd);
        if (result==1)
       {
       dispose();
       new OurCommitmentJF().setVisible(true);
       }
           }
        else
        {
            JOptionPane.showMessageDialog(null, "Sorry! Your Amount Of loan exceeds Your Current Account Balance. You Have To Deposit more.");
        }
        
        
        
        
    }//GEN-LAST:event_confirmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PayBillPageJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PayBillPageJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PayBillPageJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PayBillPageJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PayBillPageJF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AB;
    private javax.swing.JTextField ND;
    private javax.swing.JTextField PW;
    private javax.swing.JTextField WD;
    private javax.swing.JButton confirm;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
