/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package SC;

/**
 *
 * @author Jungle
 */
public class TermsAndConditionJF extends javax.swing.JFrame {

    /**
     * Creates new form TermsAndConditionPage
     */
    public TermsAndConditionJF() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TermsAndConditionjButton = new javax.swing.JButton();
        TermsAndConditionImagejLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TermsAndConditionjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SC/backbutton.jpg"))); // NOI18N
        TermsAndConditionjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TermsAndConditionjButtonActionPerformed(evt);
            }
        });
        getContentPane().add(TermsAndConditionjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 430, 260, 80));

        TermsAndConditionImagejLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SC/TermsAndCondition Image.jpg"))); // NOI18N
        getContentPane().add(TermsAndConditionImagejLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1358, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TermsAndConditionjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TermsAndConditionjButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        new RegistrationPageJF().setVisible(true);
    }//GEN-LAST:event_TermsAndConditionjButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TermsAndConditionJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TermsAndConditionJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TermsAndConditionJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TermsAndConditionJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TermsAndConditionJF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TermsAndConditionImagejLabel;
    private javax.swing.JButton TermsAndConditionjButton;
    // End of variables declaration//GEN-END:variables
}
